# AmyMialee
["2793cdc6-7710-4e7e-9d81-cf918e067729"]
"peculiarpieces:glider" = "mystery"
"peculiarpieces:anyglider" = true
"kofitable:supporter" = true

# petra_the_kat
["a2ce9382-2518-4752-87b2-c6a5c97f173e"]
"peculiarpieces:glider" = "gamma"

# will_bl
["9b035372-0d8d-4513-8bd5-9808d7f4a9b3"]
"peculiarpieces:glider" = "vampire"

# MoriyaShiine
["63a8c63b-9179-4427-849a-55212e6008bf"]
"peculiarpieces:glider" = "moriya"

# doctor4t
["1b44461a-f605-4b29-a7a9-04e649d1981c"]
"peculiarpieces:glider" = "rat"

# Techy2001
["da2d8488-8d16-409a-b25e-a5d5634b3324"]
"peculiarpieces:glider" = "classic"

# Vazkii
["8c826f34-113b-4238-a173-44639c53b6e6"]
"peculiarpieces:glider" = "tater"

# Partonetrain
["23a6dcbe-b222-4ddc-815b-9ebff5076530"]
"peculiarpieces:glider" = "tater"

# SleepyEmber
["9380b46b-8de4-4a54-b454-88f33059c9ab"]
"peculiarpieces:glider" = "tater"

# LemmaEOF
["3f5150ea-fade-4233-ad40-719e207154e9"]
"peculiarpieces:glider" = "pineapple"

# gdude2002
["1a07ce68-7eba-4609-909a-d6731a090138"]
"peculiarpieces:glider" = "pineapple"